name: test-terraform
permissions:
  contents: read

on:
  workflow_dispatch:
  pull_request:
    branches: ["main"]
    paths:
      ["config.yaml", "terraform/**", ".github/workflows/test-terraform.yml"]

defaults:
  run:
    shell: bash
    working-directory: ./terraform

jobs:
  terraform:
    name: terraform
    runs-on: ["ubuntu-latest"]
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0 https://github.com/actions/checkout/releases/tag/v7.0.0
      - uses: hashicorp/setup-terraform@dfe3c3f87815947d99a8997f908cb6525fc44e9e # v4.0.1 https://github.com/hashicorp/setup-terraform/releases/tag/v4.0.1
        with:
          terraform_version: "1.11.4"
          terraform_wrapper: false
      - name: Set up AWS & Cloudflare R2 credentials
        run: |
          mkdir -p ~/.aws
          cat > ~/.aws/credentials <<EOF
          [backend_cloudflare]
          aws_access_key_id     = ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key = ${{ secrets.AWS_SECRET_ACCESS_KEY }}

          [vpn_aws]
          aws_access_key_id     = ${{ secrets.VPN_OPS_AWS_ACCESS_KEY_ID }}
          aws_secret_access_key = ${{ secrets.VPN_OPS_AWS_SECRET_ACCESS_KEY }}
          EOF
      - run: terraform init -input=false
      - run: terraform plan -input=false
